[[redirects]]
from = "/contact"
to = "/index.html"
status = 200

[[redirects]]
from = "/bio"
to = "/index.html"
status = 200

[[redirects]]
from = "/performing"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "https://oct-n-shrk.studio/"
status = 301